module:
  hugoVersion:
    min: "0.64.0"
  mounts:
  - source: partials
    target: layouts/partials/tnd-events
  - source: console
    target: layouts/partials/tnd-events
  imports:
    - path: github.com/theNewDynamic/hugo-module-tnd-addtocal